src/OGWeb.UI/Areas/Cms/Controllers/AppSeosController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Commands.AppSeos;
using OGWeb.Core.Queries.AppSeos;

namespace OGWeb.UI.Areas.Cms.Controllers;

[Area("Cms")]
public class AppSeosController : Controller
{
    private readonly IMediator _mediator;

    public AppSeosController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var response = await _mediator.Send(new GetAllAppSeoQuery());

        return View(response.Data.ToList());
    }

    #region Create
    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateAppSeoCommand createAppSeo)
    {
        var work = await _mediator.Send(createAppSeo);

        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Edit
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await _mediator.Send(new GetAppSeoByIdQuery() { Id = id });
        if (response.Data == null)
            return NotFound();

        var overView = response.Data;

        UpdateAppSeoCommand updateAppSeo = new()
        {
            Id = response.Data.Id,
            Title = overView.Title,
            Description = overView.Description,
            Keyword = overView.Keyword,
            Page = overView.Page,
        };


        return View(updateAppSeo);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UpdateAppSeoCommand updateAppSeo)
    {
        var work = await _mediator.Send(updateAppSeo);

        return RedirectToAction(nameof(Index));
    }
    #endregion

    #region Delete
    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await _mediator.Send(new DeleteAppSeoCommand() { Id = id });
        return RedirectToAction(nameof(Index));
    }
    #endregion
}

src/OGWeb.UI/Areas/Cms/Controllers/SlidersController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Commands.Sliders;
using OGWeb.Core.Commands.Works;
using OGWeb.Core.Queries.Sliders;
using OGWeb.Core.Queries.Works;

namespace OGWeb.UI.Areas.Cms.Controllers;

[Area("Cms")]
public class SlidersController : Controller
{
    private readonly IMediator _mediator;

    public SlidersController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var response = await _mediator.Send(new GetAllSliderQuery());


        return View(response.Data.ToList());
    }

    #region Create
    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateSliderCommand createSlider)
    {
        var work = await _mediator.Send(createSlider);

        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Edit
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await _mediator.Send(new GetSliderByIdQuery() { Id = id });
        if (response.Data == null)
            return NotFound();

        var slider = response.Data;

        var UpdateSliderCommand = new UpdateSliderCommand()
        {
            Id = response.Data.Id,
            Title = slider.Title,
        };

        ViewData["ImageUrl"] = slider.ImageUrl;

        return View(UpdateSliderCommand);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UpdateSliderCommand updateSlider)
    {
        var work = await _mediator.Send(updateSlider);

        return RedirectToAction(nameof(Index));
    }
    #endregion

    #region Delete
    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await _mediator.Send(new DeleteSliderCommand() { Id = id });
        return RedirectToAction(nameof(Index));
    }
    #endregion
}

src/OGWeb.UI/Areas/Cms/Controllers/VideosController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Commands.Sliders;
using OGWeb.Core.Commands.Videos;
using OGWeb.Core.Queries.Sliders;
using OGWeb.Core.Queries.Videos;

namespace OGWeb.UI.Areas.Cms.Controllers;

[Area("Cms")]
public class VideosController : Controller
{
    private readonly IMediator _mediator;

    public VideosController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var response = await _mediator.Send(new GetAllVideoQuery());


        return View(response.Data.ToList());
    }

    #region Create
    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateVideoCommand createVideo)
    {
        var work = await _mediator.Send(createVideo);

        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Edit
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await _mediator.Send(new GetVideoByIdQuery() { Id = id });
        if (response.Data == null)
            return NotFound();

        var slider = response.Data;

        var UpdateSliderCommand = new UpdateVideoCommand()
        {
            Id = response.Data.Id,
            Title = slider.Title,
            Url = slider.Url,
            ImageUrl= slider.ImageUrl,
        };

        return View(UpdateSliderCommand);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UpdateVideoCommand updateVideo)
    {
        var work = await _mediator.Send(updateVideo);

        return RedirectToAction(nameof(Index));
    }
    #endregion

    #region Delete
    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await _mediator.Send(new DeleteVideoCommand() { Id = id });
        return RedirectToAction(nameof(Index));
    }
    #endregion
}

src/OGWeb.UI/Areas/Cms/Controllers/WorksController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Commands.Works;
using OGWeb.Core.Queries.Works;

namespace OGWeb.UI.Areas.Cms.Controllers;

[Area("Cms")]
public class WorksController : Controller
{
    private readonly IMediator _mediator;

    public WorksController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var response = await _mediator.Send(new GetAllWorkQuery());
        return View(response.Data.ToList());
    }

    #region Create
    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateWorkCommand createWork)
    {
        var work = await _mediator.Send(createWork);

        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Edit
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await _mediator.Send(new GetWorkByIdQuery() { Id = id });
        if (response.Data == null)
            return NotFound();

        var work = response.Data;

        var UpdateWorkCommand = new UpdateWorkCommand()
        {
            Id = response.Data.Id,
            Title = work.Title,
            Keyword_Seo = work.Keyword_Seo,
            CreatedDate = work.CreatedDate,
            Description = work.Description,
            Description_Seo = work.Description_Seo,
            IsActived = work.IsActived,
        };

        ViewData["ListImage"] = work.WorkFiles.ToList();

        return View(UpdateWorkCommand);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UpdateWorkCommand updateWork)
    {
        var work = await _mediator.Send(updateWork);

        return RedirectToAction(nameof(Index));
    }


    #endregion

    #region Delete

    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await _mediator.Send(new DeleteWorkCommand() { Id = id });
        return RedirectToAction(nameof(Index));
    }
    #endregion
}

src/OGWeb.UI/Areas/Cms/Views/Shared/_Layout.cshtml
@using System.Security.Claims

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - OG </title>
    <link href="https://cdn.jsdelivr.net/npm/litepicker/dist/css/litepicker.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/cms/css/styles.css" rel="stylesheet" asp-append-version=true />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="~/cms/assets/img/favicon.png" />
    <script data-search-pseudo-elements defer
            src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js"
            crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white"
             id="sidenavAccordion">
            <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0"
                    id="sidebarToggle">
                <i data-feather="menu"></i>
            </button>
            <a class="navbar-brand pe-3 ps-4 ps-lg-2" asp-controller="Home" asp-action="Index">MB Admin Pro</a>
            <ul class="navbar-nav align-items-center ms-auto">
                <li class="nav-item dropdown no-caret dropdown-user me-3 me-lg-4">
                    <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownUserImage"
                       href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <img class="img-fluid"
                             src="~/cms/assets/img/illustrations/profiles/profile-2.png" />
                    </a>
                    <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up"
                         aria-labelledby="navbarDropdownUserImage">
                        <div class="dropdown-header d-flex align-items-center">
                            <img class="dropdown-user-img"
                                 src="~/cms/assets/img/illustrations/profiles/profile-2.png" />
                            <div class="dropdown-user-details">
                                <div class="dropdown-user-details-name">@User.Identity?.Name</div>
                                <div class="dropdown-user-details-email">@User.FindFirst(ClaimTypes.Email)?.Value</div>
                            </div>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-area="Cms" asp-controller="Account" asp-action="Logout">
                            <div class="dropdown-item-icon"><i data-feather="log-out"></i></div>
                            Çıkış Yap
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sidenav shadow-right sidenav-light">
                <div class="sidenav-menu">
                    <div class="nav accordion" id="accordionSidenav">
                        <div class="sidenav-menu-heading">Ana Sayfa</div>
                        <!-- Sidenav Accordion (Dashboard)-->
                        <a class="nav-link" asp-area="Cms" asp-controller="Home" asp-action="Index">
                            <div class="nav-link-icon"><i data-feather="activity"></i></div>
                            Ana Sayfa
                        </a>
                        <!-- Sidenav Heading (Custom)-->
                        <div class="sidenav-menu-heading">Cms Sayfaları</div>
                        <!-- Sidenav Accordion (Pages)-->
                        <a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse"
                           data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="nav-link-icon"><i data-feather="grid"></i></div>
                            Sayfalar
                            <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" data-bs-parent="#accordionSidenav">
                            <nav class="sidenav-menu-nested nav accordion" id="accordionSidenavPagesMenu">
                                <a class="nav-link" asp-area="Cms" asp-controller="Sliders" asp-action="Index">Slayder</a>
                                <a class="nav-link" asp-area="Cms" asp-controller="Works" asp-action="Index">İşler</a>
                                <a class="nav-link" asp-area="Cms" asp-controller="Videos" asp-action="Index">Videolar</a>
                                <a class="nav-link" asp-area="Cms" asp-controller="OverViews" asp-action="Index">Hakkımda</a>

                            </nav>
                        </div>
                        <div class="sidenav-menu-heading">Ayarlar</div>
                        <a class="nav-link" asp-area="Cms" asp-controller="AppSeos" asp-action="Index">
                            <div class="nav-link-icon"><i data-feather="tool"></i></div>
                            Sayfa Seo Ayarları
                        </a>
                        <a class="nav-link" asp-area="Cms" asp-controller="AppSettings" asp-action="Index">
                            <div class="nav-link-icon"><i data-feather="settings"></i></div>
                            Genel Ayarlar
                        </a>
                    </div>
                </div>
                <!-- Sidenav Footer-->
                <div class="sidenav-footer">
                    <div class="sidenav-footer-content">
                        <div class="sidenav-footer-subtitle">Giriş yaptı:</div>
                        <div class="sidenav-footer-title">@User.Identity?.Name</div>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <!-- Main page content-->
                @RenderBody()
            </main>
            <footer class="footer-admin mt-auto footer-light">
                <div class="container-xl px-4">
                    <div class="row">
                        <div class="col-md-6 small">&copy; OG @DateTime.Now.Year</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/litepicker/dist/bundle.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
            crossorigin="anonymous"></script>
    <script src="~/cms/js/litepicker.js"></script>

    <script src="~/cms/js/datatables/datatables-simple-demo.js"></script>
    <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/cms/js/scripts.js" asp-append-version="true"></script>
    @{
        await Html.RenderPartialAsync("_MessagesModal");
    }
</body>

</html>

src/OGWeb.UI/Areas/Cms/Views/Shared/_MessagesModal.cshtml
@if (TempData["Success"] != null || TempData["Error"] != null || TempData["Warning"] != null || TempData["Info"] != null)
{
    <script>
    @if (TempData["Success"] != null) {
        <Text>
            toastr.success('@TempData["Success"]');
        </text>

     }
     @if (TempData["Error"] != null) {
        <Text>
            toastr.error('@TempData["Error"]');
        </text>

       }
      @if (TempData["Warning"] != null) {
        <Text>
            toastr.warning('@TempData["Warning"]');
        </text>

       }
       @if (TempData["Info"] != null) {
        <Text>
            toastr.info('@TempData["Info"]');
        </text>

        }
    </script>
}