src/OGWeb.UI/Areas/Cms/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OGWeb.UI.Areas.Cms.Controllers;

[Area("Cms")]
public class HomeController : Controller
{
    [Route("/cms")]
    public IActionResult Index()
    {
        return View();
    }
}

src/OGWeb.UI/Areas/Cms/Controllers/VideosController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Commands.Sliders;
using OGWeb.Core.Commands.Videos;
using OGWeb.Core.Queries.Sliders;
using OGWeb.Core.Queries.Videos;

namespace OGWeb.UI.Areas.Cms.Controllers;

[Area("Cms")]
public class VideosController : Controller
{
    private readonly IMediator _mediator;

    public VideosController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var response = await _mediator.Send(new GetAllVideoQuery());


        return View(response.Data.ToList());
    }

    #region Create
    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateVideoCommand createVideo)
    {
        var work = await _mediator.Send(createVideo);

        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Edit
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await _mediator.Send(new GetVideoByIdQuery() { Id = id });
        if (response.Data == null)
            return NotFound();

        var slider = response.Data;

        var UpdateSliderCommand = new UpdateVideoCommand()
        {
            Id = response.Data.Id,
            Title = slider.Title,
            Url = slider.Url,
            ImageUrl= slider.ImageUrl,
        };

        return View(UpdateSliderCommand);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UpdateVideoCommand updateVideo)
    {
        var work = await _mediator.Send(updateVideo);

        return RedirectToAction(nameof(Index));
    }
    #endregion

    #region Delete
    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await _mediator.Send(new DeleteVideoCommand() { Id = id });
        return RedirectToAction(nameof(Index));
    }
    #endregion
}

src/OGWeb.UI/Areas/Cms/Controllers/WorksController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Commands.Works;
using OGWeb.Core.Queries.Works;

namespace OGWeb.UI.Areas.Cms.Controllers;

[Area("Cms")]
public class WorksController : Controller
{
    private readonly IMediator _mediator;

    public WorksController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var response = await _mediator.Send(new GetAllWorkQuery());
        return View(response.Data.ToList());
    }

    #region Create
    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateWorkCommand createWork)
    {
        var work = await _mediator.Send(createWork);

        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Edit
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await _mediator.Send(new GetWorkByIdQuery() { Id = id });
        if (response.Data == null)
            return NotFound();

        var work = response.Data;

        var UpdateWorkCommand = new UpdateWorkCommand()
        {
            Id = response.Data.Id,
            Title = work.Title,
            Keyword_Seo = work.Keyword_Seo,
            CreatedDate = work.CreatedDate,
            Description = work.Description,
            Description_Seo = work.Description_Seo,
            IsActived = work.IsActived,
        };

        ViewData["ListImage"] = work.WorkFiles.ToList();

        return View(UpdateWorkCommand);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UpdateWorkCommand updateWork)
    {
        var work = await _mediator.Send(updateWork);

        return RedirectToAction(nameof(Index));
    }


    #endregion

    #region Delete

    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await _mediator.Send(new DeleteWorkCommand() { Id = id });
        return RedirectToAction(nameof(Index));
    }
    #endregion
}

src/OGWeb.UI/Components/FooterViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Queries.AppSettings;

namespace OGWeb.UI.Components;

public class FooterViewComponent : ViewComponent
{
    private readonly IMediator _mediator;

    public FooterViewComponent(IMediator mediator)
    {
        _mediator = mediator;
    }
    public async Task<IViewComponentResult> InvokeAsync(string page = null!)
    {
        var configs = await _mediator.Send(new GetAppSettingByQuery());

        ViewData["page"] = page;

        return View(configs.Data);
    }
}

src/OGWeb.UI/Components/SeoViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Queries.AppSeos;

namespace OGWeb.UI.Components;

public class SeoViewComponent: ViewComponent
{
    private readonly IMediator _mediator;

    public SeoViewComponent(IMediator mediator)
    {
        _mediator = mediator;
    }
    public async Task<IViewComponentResult> InvokeAsync(string page = null!)
    {
        var response = await _mediator.Send(new GetAppSeoByPageQuery() { Page = page });

        return View(response.Data);
    }
}

src/OGWeb.UI/Controllers/HomeController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using OGWeb.Core.Queries.OverViews;
using OGWeb.Core.Queries.Sliders;
using OGWeb.Core.Queries.Videos;
using OGWeb.Core.Queries.Works;
using OGWeb.UI.Models;
using System.Diagnostics;

namespace OGWeb.UI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IMediator _mediator;

    public HomeController(ILogger<HomeController> logger, IMediator mediator)
    {
        _logger = logger;
        _mediator = mediator;
    }

    [Route("/")]
    public async Task<IActionResult> Index()
    {
        _logger.LogInformation("Ana Sayfa");

        var response = await _mediator.Send(new GetAllSliderQuery());

        return View(response.Data.ToList());
    }

    [Route("/works")]
    public async Task<IActionResult> Work()
    {
        _logger.LogInformation("Ana Sayfa");

        var response = await _mediator.Send(new GetAllWorkQuery());

        return View(response.Data.ToList());
    }

    [Route("/works/{id}")]
    public async Task<IActionResult> WorkDetail(Guid id)
    {
        _logger.LogInformation("Ana Sayfa");

        var response = await _mediator.Send(new GetWorkByIdQuery() { Id = id });

        return View(response.Data);
    }

    [Route("/overview")]
    public async Task<IActionResult> OverView()
    {
        _logger.LogInformation("Hakkimizda");

        var response = await _mediator.Send(new GetAllOverViewQuery());

        return View(response.Data.ToList());
    }

    [Route("/videos")]
    public async Task<IActionResult> Video()
    {
        _logger.LogInformation("Video");

        var response = await _mediator.Send(new GetAllVideoQuery());

        return View(response.Data.ToList());
    }

    [Route("/contact")]
    public IActionResult Contact()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/OGWeb.UI/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
@section Seo{
    @await Component.InvokeAsync("Seo", new { page = "Contact"  })
}
<section class="bg-black d-flex flex-column align-items-center justify-content-between pb-3">
    <div class="container">
        <div class="section-main pb-5">
            <div class="contact-main d-flex align-items-center flex-column">
                <p class="partner-heading text-center">Contact</p>
                <form autocomplete="off" class="col-12 col-lg-9 col-xl-6 col-xxl-4 mx-auto">
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                        <label for="floatingInput">Name</label>
                    </div>
                    <div class="form-floating mb-4">
                        <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                        <label for="floatingInput">Email</label>
                    </div>
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                        <label for="floatingInput">Subject</label>
                    </div>
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                        <label for="floatingInput">Your Message</label>
                    </div>
                    <button type="submit" class="btn btn-send d-flex align-items-center">
                        Göndər
                        <i class="bi bi-arrow-right-short ms-3"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
    @await Component.InvokeAsync("Footer")
</section>
@section Plugins{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.2.0/sweetalert2.all.min.js"></script>
}
    @section Scripts{
    <script>
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            iconColor: 'white',
            customClass: {
                popup: 'colored-toast'
            },
            showConfirmButton: false,
            timer: 3000,
        });
    </script>
}

src/OGWeb.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using OGWeb.Core.Dtos
@model List<SliderDto>

@section Seo{
    @await Component.InvokeAsync("Seo", new { page = "Home"  })
}



@foreach (var item in Model)
{
    <section class="home-section bg-black d-flex flex-column align-items-center justify-content-between"
         style="background-image: url(/@item.ImageUrl);">
        <div class="container">
            <div class="section-main">
                <div class="home-main d-flex align-content-center justify-content-center flex-column">
                    <div class="home-text">
                        <h1 class="glitch" data-text="@item.Title">@item.Title</h1>
                        <h3>Onat Gökçen</h3>
                    </div>
                </div>
            </div>
        </div>
        @await Component.InvokeAsync("Footer", new { page = "Home"  })
    </section>
}

src/OGWeb.UI/Views/Home/OverView.cshtml
@using OGWeb.Core.Dtos
@model List<OverViewDto>

@section Seo{
    @await Component.InvokeAsync("Seo", new { page = "OverView"  })
}

<section class="bg-black d-flex flex-column align-items-center justify-content-between pb-3">
    <div class="container">
        <div class="section-main pb-5">
            @foreach (var item in Model)
            {
                <div class="about-main d-flex align-items-center justify-content-center">
                    <div class="row w-100 g-0">
                        <div class="col-12 col-lg-7 left mb-5 mb-lg-0" data-aos="fade-right" data-aos-offset="100"
                         data-aos-easing="ease-in-sine">
                            <h2>@item.Title</h2>
                            @Html.Raw(item.Description)
                        </div>
                        <div class="col-12 col-lg-4 offset-lg-1 right">
                            <div class="about-big-image" data-aos="fade-left" data-aos-anchor="#example-anchor"
                             data-aos-offset="600" data-aos-duration="600">
                                <img src="/@item.ImageUrl_One" alt="">
                            </div>
                            <div class="about-small-image" data-aos="fade-left" data-aos-duration="900">
                                <img src="/@item.ImageUrl_Two" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
    @await Component.InvokeAsync("Footer")
</section>
@section Plugins{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
}
    @section Scripts{
    <script>
        AOS.init({
            once: 'true'
        });
        ScrollReveal().reveal('.widget .video-card', {
            delay: 500,
            useDelay: 'onload',
        })

        ScrollReveal().reveal('.widget .video-card', {
            delay: 0,
            interval: 250
        })
    </script>
}

src/OGWeb.UI/Views/Home/Video.cshtml
@using OGWeb.Core.Dtos
@model List<VideoDto>

@section Seo{
    @await Component.InvokeAsync("Seo", new { page = "Video"  })
}


<section class="bg-black d-flex flex-column align-items-center justify-content-between pb-3">
    <div class="container">
        <div class="section-main pb-5">
            <div class="video-main d-flex align-items-center flex-column">
                <p class="partner-heading text-center">Videos</p>
                <div class="row row-cols-1 row-cols-md-2 g-5 mt-2">
                    @foreach (var item in Model)
                    {
                        <div class="col widget">
                            <a href="@item.Url"
                           class="video-card d-block position-relative glightbox2">
                                <img src="/@item.ImageUrl" alt="@item.Title">
                                <i class="bi bi-play-circle-fill position-absolute top-50 start-50 translate-middle"></i>
                            </a>
                        </div>
                    }
                    
                </div>
            </div>
        </div>
    </div>
    @await Component.InvokeAsync("Footer")
</section>
@section Plugins{
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
}
    @section Scripts{
    <script>
        var lightbox = GLightbox();
        var lightboxDescription = GLightbox({
            selector: '.glightbox2'
        });
        ScrollReveal().reveal('.widget .video-card', {
            delay: 500,
            useDelay: 'onload',
        })

        ScrollReveal().reveal('.widget .video-card', {
            delay: 0,
            interval: 250
        })
    </script>
}

src/OGWeb.UI/Views/Home/Work.cshtml
@using OGWeb.Core.Dtos
@model List<WorkListDto>

@section Seo{
    @await Component.InvokeAsync("Seo", new { page = "Work"  })
}


<section class="bg-black d-flex flex-column align-items-center justify-content-between pb-3">
    <div class="container">
        <div class="section-main pb-5">
            <div class="work-main d-flex align-items-center flex-column">
                <p class="partner-heading text-center">Works</p>
                <div class="work-cols-main">
                    @foreach (var item in Model)
                    {
                        <a asp-controller="Home" asp-action="WorkDetail" asp-route-id="@item.Id" class="works-card">
                            <img class="works-image" src="/@item.Path" alt="works">
                            <p class="position-absolute top-50 start-50 translate-middle">
                                @item.Title
                            </p>
                            <i class="bi bi-arrow-right-short"></i>
                        </a>
                    }

                </div>
            </div>
        </div>
    </div>
    @await Component.InvokeAsync("Footer")
</section>
@section Plugins{
    <script src="https://unpkg.com/scrollreveal"></script>
}
    @section Scripts{
    <script>
        ScrollReveal().reveal('.work-cols-main .works-card', {
            delay: 0,
            interval: 180
        });
    </script>
}

src/OGWeb.UI/Views/Home/WorkDetail.cshtml
@using OGWeb.Core.Dtos
@model WorkDto

@section Seo{

    <meta name="title" content="@Model.Title">
    <meta name="keywords" content="@Model.Keyword_Seo">
    <meta name="description" content="@Model.Description_Seo">

    <title>Model.Title </title>
}


    <section class="work-detail-section bg-black d-flex flex-column align-items-center justify-content-between pb-3">
        <div class="container">
            <div class="section-main pb-5">
                <div class="work-detail-main d-flex align-items-center  flex-column col-12 col-lg-9 col-xl-8 col-xxl-7 mx-auto detail-main">
                    <h1 class="work-detail-heading">
                        @Model.Title
                    </h1>
                    @Html.Raw(Model.Description)
                    <div class="swiper mahsul-detay-slider px-4 px-lg-0">
                        <div class="swiper-wrapper">
                        @foreach (var item in Model.WorkFiles)
                        {
                            <div class="swiper-slide">
                                <img src="/@item.ImageUrl" class="swiper-lazy" />
                            </div>
                        }
                    </div>
                    <div class="swiper-navs">
                        <button class="btn swiper-prev">
                            <i class="bi bi-arrow-left-short"></i>
                        </button>
                        <button class="btn swiper-next">
                            <i class="bi bi-arrow-right-short"></i>
                        </button>
                    </div>

                </div>
            </div>
        </div>
    </div>
    @await Component.InvokeAsync("Footer")
</section>
@section Plugins{
    <script src="https://unpkg.com/scrollreveal"></script>
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
}
    @section Scripts{
    <script>
        ScrollReveal().reveal('.work-cols-main .works-card', {
            delay: 0,
            interval: 180
        })
    </script>
}